### ISSUE TITLE
Git commit mesajı

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [xgusein/PragmatechFrontendProject#1]
_Hüseyn, commit mesajların səhvdir. [Bu](https://serdarkuzucu.com/2020/04/19/git-commit-mesaji-nasil-yazilmali/) və [bu](https://chiamakaikeanyi.dev/how-to-write-good-git-commit-messages/) linkdəki qaynaqlara bir göz at. :)_

**Comment by xgusein** [comment]
Çox təşəkkürlər.
